= Efficient Trace for RISC-V
Gajinder Panesar <gajinder.panesar@gmail.com>, Iain Robertson <iain.robertson@siemens.com>
:description: Efficient Trace for RISC-V
:company: RISC-V.org
:revdate: TBD, 2026
:revnumber: 2.0
:url-riscv: http://riscv.org
:doctype: book
:pdf-theme: docs-resources/themes/riscv-pdf.yml
:pdf-fontsdir: ../src/resources/fonts/
:preface-title: Preamble
:colophon:
:pdf-theme: docs-resources/themes/riscv-pdf.yml
:pdf-fontsdir: docs-resources/fonts/
:appendix-caption: Appendix
:imagesdir: images
:title-logo-image: image:risc-v_logo.svg[pdfwidth=3.25in,align=center]
// Settings:
:experimental:
:reproducible:
//:WaveDromEditorApp: app/wavedrom-editor.app
:imagesoutdir: images
//:bibtex-file: example.bib
//:bibtex-order: alphabetical
//:bibtex-style: apa
:icons: font
:lang: en
:listing-caption: Listing
:sectnums:
:media: prepress
:!show-link-uri:
:toc: left
:toclevels: 4
:source-highlighter: pygments
ifdef::backend-pdf[]
:source-highlighter: coderay
endif::[]
:data-uri:
:hide-uri-scheme:
:stem: latexmath
:footnote:
:xrefstyle: short

[preface]
== Copyright and license information
This specification is licensed under the Creative Commons
Attribution 4.0 International License (CC-BY 4.0). The full
license text is available at
https://creativecommons.org/licenses/by/4.0/.

Copyright 2025 by RISC-V International.

[colophon]
*_Preface to Version TBD_*

* Add <<sec:ext-impret>>, which describes the Implicit Return extension to Version 2.0.
* Updated the decoder pseudo-code in <<Decoder>> to include support for Implicit Return, Branch Predictor and Jump Target Cache optional modes.

*_Preface to Version 20250616_*

Clarifications only - no changes to normative behaviour.

* Updated <<packets>> and <<fragments>> to reference the https://github.com/riscv-non-isa/e-trace-encap/releases/latest/[Unformatted Trace & Diagnostic Data Packet Encapsulation for RISC-V Specification];
* Removed ambiguity between 'last' and 'final'.  Last was previously used to mean both the instruction before the current one, and the final instruction traced;
* Clarified behaviour when trace-on and trace-off triggers occur both occur in the same cycle (see <<sec:trigger>>);
* Clarified that full synchronization also takes place on a privilege change (see <<sec:synchronization>> and <<sec:thaddr>>);
* Reworded jump classifications in jump classifications in <<sec:InstructionInterfaceRequirements>> to align with terminology used in other specifications;
* Clarified when to issue sync-support packet when trace is enabled (see <<sec:format33>>);
* Clarified that branch_map can be set to 31 any time an address needs to be reported and the branch map is full (see <<sec:format1>>);
* Updated reference encoding algorithm to generalize resync behaviour and add missing trap conditions (see <<Algorithm>>);
* Clarified that implicit returns are not stored in the jump target cache (see <<sec:jump-cache>>);
* Updated decoder to remove ECALL, EBREAK and C.EBREAK from is_uninferrable_jump function.  Including them is harmless but unnecessary, as these instrucitons don't retire (see <<Decoder>>);
* Corrected description of why the EPC is not always reported (see <<sec:thaddr>>).
* Minor clarifications, formatting and typo fixes.

*_Preface to Version 20240419_*

Formatting and typo fixes.

*_Preface to Version 20240305_*

First version in AsciiDoc format.

*_Preface to Version 20231215_*

Clarifications only - no changes to normative behaviour.

* Control field definitions removed from section 2, which now references the xref:https://github.com/riscv-non-isa/e-trace-encap/releases/latest/[RISC-V Trace Control Interface Specification]
* Added detail on handling of multi-load/store instructions for data trace to <<sec:DataInterfaceRequirements>>.
* Removed references to tail-calls in jump classifications in <<sec:InstructionInterfaceRequirements>>.
* Corrected typos where `lrid` was inadvertently refered to by an earlier name (`index`) in <<sec:data-loadstore>>.
* Corrected reference decoder in <<Decoder>> to cover a corner-case related to trap returns.

*_Preface to Version 2.0_*

Ratified version of the Efficient Trace for RISC-V specification.


include::introduction.adoc[]
include::control.adoc[]
include::branchTrace.adoc[]
include::ingressPort.adoc[]
include::filtering.adoc[]
include::timestamping.adoc[]
include::payload.adoc[]
include::dataTracePayload.adoc[]
include::exampleAlgorithm.adoc[]
include::discovery.adoc[]
include::decoder.adoc[]
include::exampleCodeSnippets.adoc[]
include::fragmentCodeAndTransport.adoc[]
include::extensions.adoc[]
include::future.adoc[]
//include::index.adoc[]
//include::bibliography.adoc[]
